"""
Agent orchestration module for the World Cup Squad Builder.

Owner:
    Person C

Purpose:
    - Configure a LangChain agent that can:
        * Use tools for data ingestion, retrieval, reasoning, and report generation.
        * Maintain conversational memory across user turns (e.g., preferences).
        * Follow a ReAct-style reasoning pattern to decide when and how to use tools.
    - Provide a simple interface (`create_agent`, `run_query`) for the Gradio UI
      and the Jupyter notebook demo.

Dependencies (for eventual implementation):
    - `langchain_openai.ChatOpenAI`
    - `langchain.agents.create_react_agent`, `langchain.agents.AgentExecutor`
      OR `langchain.agents.initialize_agent`, `langchain.agents.AgentType`
    - `langchain.memory.ConversationBufferMemory`
    - `src.tools` (for tool definitions)
    - `src.prompts.AGENT_SYSTEM_PROMPT`

Memory requirements:
    - Use `ConversationBufferMemory` with at least:
        * `memory_key="chat_history"`
    - Must persist at least two user preferences across turns
      (e.g., formation style, budget, age preference).

ReAct behavior:
    - The agent should follow the Thought → Action → Action Input → Observation
      loop pattern, as demonstrated in class labs.
"""

from typing import Any


def create_agent() -> Any:
    """
    Create and configure the LangChain agent for the World Cup Squad Builder.

    Responsibilities:
        - Initialize a `ChatOpenAI` LLM instance with appropriate parameters
          (e.g., model name, temperature).
        - Import and register tools from `src.tools`, such as:
            * data_ingestion_tool
            * retrieval_or_filter_tool
            * reasoning_or_aggregation_tool
            * report_generation_tool
        - Configure `ConversationBufferMemory` to persist conversation history
          and at least two user preferences across multiple turns.
        - Construct the agent using either:
            * Option A: `create_react_agent` and `AgentExecutor`, or
            * Option B: `initialize_agent` with `AgentType.ZERO_SHOT_REACT_DESCRIPTION`.
        - Incorporate `AGENT_SYSTEM_PROMPT` as the system or prefix prompt to
          clearly define the agent's role and how it should use tools.

    Parameters:
        None.

    Returns:
        An `AgentExecutor`-like object (or equivalent) that can be invoked with
        user input and will internally manage tool calls and memory.

    Notes for implementation:
        - Use `verbose=True` during development to visualize the reasoning chain
          in the notebook, which is important for grading.
        - Ensure that the agent is robust to errors from tools and provides
          helpful messages when something goes wrong.
    """
    pass


def run_query(agent: Any, user_input: str) -> str:
    """
    Run a user query through the configured agent and return the final response.

    Responsibilities:
        - Accept a string `user_input` from the UI or notebook.
        - Invoke the agent (e.g., `agent.invoke` or `agent.run`) with the input
          and current memory state.
        - Capture the final response string from the agent, which may include
          a synthesized squad report or intermediate explanation.
        - Handle and gracefully report any errors that occur during tool calls
          or agent reasoning.

    Parameters:
        agent:
            The agent object returned by `create_agent`.
        user_input:
            The current user message, such as:
                "Build me a World Cup squad with fast attackers and strong defenders,
                 budget under 500000 EUR."
                or
                "Now make it cheaper while keeping a focus on pace."
        Returns:
            A final response string generated by the agent, suitable for display
            in the Gradio interface or notebook.

    Notes for implementation:
        - This function should be thin and primarily responsible for error
          handling and consistent return types.
        - Memory updates should be managed by the agent and its configured
          `ConversationBufferMemory`.
    """
    pass

